// Sample data - In production, this would come from your API
export const sampleData = {
  buyer: {
    name: "Sarah",
    email: "sarah.johnson@email.com",
    phone: "(555) 123-4567",
  },
  dealership: {
    name: "Heritage Honda",
    logo: undefined as string | undefined,
    rating: {
      stars: 4.7,
      count: 3124,
    },
  },
  vehicle: {
    year: 2025,
    make: "Honda",
    model: "CR-V",
    trim: "Sport Touring Hybrid",
    price: 39845,
    mileage: 12,
    fuelType: "Hybrid",
    transmission: "CVT",
    photos: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
      "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80",
    ],
    carfaxUrl: "https://www.carfax.com",
    features: [
      {
        id: "1",
        name: "Panoramic Moonroof",
        description: "Expansive glass roof that floods the cabin with natural light. One-touch open and tilt controls.",
        category: "Comfort",
        position: { x: 50, y: 20 },
        closeUpImage: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=400&q=80",
      },
      {
        id: "2",
        name: "Leather-Trimmed Seats",
        description: "Heated and ventilated front seats with 12-way power adjustment and memory settings.",
        category: "Interior",
        position: { x: 35, y: 55 },
        closeUpImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&q=80",
      },
      {
        id: "3",
        name: "Honda Sensing 360",
        description: "Complete suite of advanced safety and driver-assist features including blind spot info and front cross traffic monitor.",
        category: "Safety",
        position: { x: 15, y: 75 },
      },
      {
        id: "4",
        name: "Bose Premium Audio",
        description: "12-speaker Bose premium sound system with centerpoint surround technology.",
        category: "Technology",
        position: { x: 70, y: 50 },
      },
    ],
    walkaroundVideo: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  },
  salesperson: {
    name: "David Nakamura",
    title: "Honda Brand Specialist",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    bio: "With over 10 years at Heritage Honda, I love helping families find the right Honda for their lifestyle. Whether it is your first Honda or your fifth, I am here to make the process easy and enjoyable.",
    phone: "(555) 987-6543",
    email: "david.nakamura@heritagehonda.com",
    introVideo: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  },
  reviews: [
    {
      id: "1",
      reviewerName: "Jennifer M.",
      rating: 5,
      excerpt: "David went above and beyond to help us find exactly what we were looking for. No pressure, just great service. Our third Honda from Heritage!",
      source: "google" as const,
      isSalespersonReview: true,
    },
    {
      id: "2",
      reviewerName: "Robert K.",
      rating: 5,
      excerpt: "Best car buying experience I have ever had. The team was professional and the entire process was smooth from start to finish.",
      source: "dealerrater" as const,
    },
    {
      id: "3",
      reviewerName: "Amanda L.",
      rating: 4,
      excerpt: "Great selection of Hondas and fair pricing. The staff really knows their inventory and helped me compare the CR-V trims side by side.",
      source: "yelp" as const,
    },
    {
      id: "4",
      reviewerName: "Marcus T.",
      rating: 5,
      excerpt: "David made the whole process painless. He answered all my questions and never made me feel rushed. Highly recommend Heritage Honda!",
      source: "facebook" as const,
      isSalespersonReview: true,
    },
    {
      id: "5",
      reviewerName: "Lisa W.",
      rating: 5,
      excerpt: "Drove away in our new CR-V the same day. Financing was easy and everyone was so helpful. Thank you Heritage Honda!",
      source: "carscom" as const,
    },
  ],
}

// Modern theme sample data - tech-forward dealership (Tesla-style)
export const sampleDataModern = {
  buyer: {
    name: "Sarah",
    email: "sarah.johnson@email.com",
    phone: "(555) 123-4567",
  },
  dealership: {
    name: "Velocity Auto",
    logo: undefined as string | undefined,
    rating: {
      stars: 4.8,
      count: 2156,
    },
  },
  vehicle: {
    year: 2025,
    make: "Tesla",
    model: "Model Y",
    trim: "Long Range AWD",
    price: 52990,
    mileage: 156,
    fuelType: "Electric",
    transmission: "Single-Speed",
    photos: [
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80",
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80",
      "https://images.unsplash.com/photo-1620891549027-942fdc95d3f5?w=800&q=80",
      "https://images.unsplash.com/photo-1619317142793-219f04b42a6c?w=800&q=80",
      "https://images.unsplash.com/photo-1571127236794-81c0bbfe1ce3?w=800&q=80",
    ],
    carfaxUrl: "https://www.carfax.com",
    features: [
      {
        id: "1",
        name: "Full Self-Driving",
        description: "Navigate on Autopilot, Auto Lane Change, Autopark, and Summon capabilities with continuous software updates.",
        category: "Technology",
        position: { x: 50, y: 25 },
        closeUpImage: "https://images.unsplash.com/photo-1620891549027-942fdc95d3f5?w=400&q=80",
      },
      {
        id: "2",
        name: "Premium Interior",
        description: "Vegan leather seating, 15-inch touchscreen, immersive sound system, and panoramic glass roof.",
        category: "Interior",
        position: { x: 35, y: 55 },
        closeUpImage: "https://images.unsplash.com/photo-1619317142793-219f04b42a6c?w=400&q=80",
      },
      {
        id: "3",
        name: "330mi Range",
        description: "Estimated EPA range of 330 miles on a single charge with access to 45,000+ Superchargers.",
        category: "Performance",
        position: { x: 15, y: 75 },
      },
      {
        id: "4",
        name: "Over-the-Air Updates",
        description: "Continuous improvements and new features delivered wirelessly while you sleep.",
        category: "Software",
        position: { x: 70, y: 45 },
      },
    ],
    walkaroundVideo: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  },
  salesperson: {
    name: "Alex Rivera",
    title: "EV Specialist",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    bio: "As a certified EV specialist, I help customers transition to electric with confidence. From charging infrastructure to software features, I make the future of driving accessible.",
    phone: "(555) 987-6543",
    email: "alex.rivera@velocityauto.com",
    introVideo: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  },
  reviews: [
    {
      id: "1",
      reviewerName: "Chris M.",
      rating: 5,
      excerpt: "Alex made my first EV purchase seamless. Walked me through every feature and even helped set up home charging. Incredible service!",
      source: "google" as const,
      isSalespersonReview: true,
    },
    {
      id: "2",
      reviewerName: "Priya S.",
      rating: 5,
      excerpt: "Velocity Auto has the best EV selection in the area. The team really understands electric vehicles inside and out.",
      source: "dealerrater" as const,
    },
    {
      id: "3",
      reviewerName: "Jordan T.",
      rating: 4,
      excerpt: "Great experience overall. The online booking and paperless process made everything super efficient.",
      source: "yelp" as const,
    },
    {
      id: "4",
      reviewerName: "Michelle K.",
      rating: 5,
      excerpt: "Alex answered every question I had about range anxiety and charging. Now I cant imagine going back to gas!",
      source: "facebook" as const,
      isSalespersonReview: true,
    },
    {
      id: "5",
      reviewerName: "David H.",
      rating: 5,
      excerpt: "The future is electric, and Velocity Auto is leading the way. Professional, knowledgeable, and genuinely helpful.",
      source: "carscom" as const,
    },
  ],
}

// Prestige theme sample data - luxury dealership
export const prestigeData = {
  buyer: {
    name: "Sarah",
    email: "sarah.johnson@email.com",
    phone: "(555) 123-4567",
  },
  dealership: {
    name: "Prestige Motors",
    logo: undefined as string | undefined,
    rating: {
      stars: 4.9,
      count: 1847,
    },
  },
  vehicle: {
    year: 2025,
    make: "BMW",
    model: "X5",
    trim: "xDrive40i M Sport",
    price: 72995,
    mileage: 847,
    fuelType: "Premium Gasoline",
    transmission: "8-Speed Automatic",
    photos: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&q=80",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
    ],
    carfaxUrl: "https://www.carfax.com",
    features: [
      {
        id: "1",
        name: "Panoramic Sky Lounge",
        description: "Full-length glass roof with LED ambient lighting that illuminates the cabin in six different colors.",
        category: "Luxury",
        position: { x: 50, y: 20 },
        closeUpImage: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&q=80",
      },
      {
        id: "2",
        name: "Vernasca Leather",
        description: "Hand-stitched Vernasca leather upholstery with contrast stitching and 20-way power seats.",
        category: "Interior",
        position: { x: 35, y: 55 },
        closeUpImage: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&q=80",
      },
      {
        id: "3",
        name: "M Sport Brakes",
        description: "High-performance M Sport braking system with blue calipers and enhanced stopping power.",
        category: "Performance",
        position: { x: 15, y: 75 },
      },
      {
        id: "4",
        name: "Harman Kardon Surround",
        description: "16-speaker Harman Kardon surround sound system with 600 watts of crystalline audio.",
        category: "Technology",
        position: { x: 70, y: 50 },
      },
    ],
    walkaroundVideo: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  },
  salesperson: {
    name: "Michael Chen",
    title: "Senior Sales Consultant",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    bio: "With over 12 years at Prestige Motors, I specialize in curating the perfect luxury vehicle experience. Every client deserves white-glove service and my full attention to detail.",
    phone: "(555) 987-6543",
    email: "michael.chen@prestigemotors.com",
    introVideo: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  },
  reviews: [
    {
      id: "1",
      reviewerName: "Alexandra R.",
      rating: 5,
      excerpt: "Michael provided an exceptional experience from start to finish. The attention to detail and personalized service exceeded all expectations.",
      source: "google" as const,
      isSalespersonReview: true,
    },
    {
      id: "2",
      reviewerName: "Jonathan K.",
      rating: 5,
      excerpt: "Prestige Motors lives up to its name. The facility is immaculate and the team treats you like royalty.",
      source: "dealerrater" as const,
    },
    {
      id: "3",
      reviewerName: "Victoria S.",
      rating: 5,
      excerpt: "This is how luxury car buying should be. No pressure, just expert guidance and impeccable service.",
      source: "yelp" as const,
    },
    {
      id: "4",
      reviewerName: "Marcus W.",
      rating: 5,
      excerpt: "Michael made me feel like I was his only client. He went above and beyond to ensure everything was perfect.",
      source: "facebook" as const,
      isSalespersonReview: true,
    },
    {
      id: "5",
      reviewerName: "Catherine L.",
      rating: 5,
      excerpt: "From the moment I walked in to driving away in my new X5, every detail was handled with care. Truly a premium experience.",
      source: "carscom" as const,
    },
  ],
}
